from src.drawings_catagories.ICountries import ICountries
from colorama import init
from colorama import Fore, Back, Style

class CountriesNormal(ICountries):
    def draw_countries(self, number):
        counries_list =[[ 
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                    " + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####\|" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####\|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####\|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
            [Fore.BLUE + "#              "+ Fore.WHITE +"                   I" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####/|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     ------+------ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     $$$$$$|$$$$$$ |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"     #####$|$#####\|" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#              "+ Fore.WHITE +"                   |" + Fore.BLUE +"               #",
            Fore.BLUE + "#               "+ Fore.WHITE +"===================" + Fore.BLUE +"               #"],
        ]

        self.print_countries(counries_list,number-1)




